function createfigure(ymatrix1, ymatrix2, ymatrix3)
%CREATEFIGURE(ymatrix1, ymatrix2, ymatrix3)
%  YMATRIX1:  bar matrix data
%  YMATRIX2:  bar matrix data
%  YMATRIX3:  bar matrix data

%  Auto-generated by MATLAB on 26-Sep-2020 01:34:00

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.758333333333333 5 4.52083333333333 2.47916666666667],...
    'Units','inches');
hold(axes1,'on');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1,'Parent',axes1);
set(bar1(6),'DisplayName','Matpower (a)','FaceColor','none','BarWidth',1);
set(bar1(5),'DisplayName','Matpower (b)','FaceColor','none','BarWidth',1);
set(bar1(4),'DisplayName','Matpower (c)','FaceColor','none','BarWidth',1);
set(bar1(3),'DisplayName','a','FaceColor',[0 0 1],'BarWidth',0.5);
set(bar1(2),'DisplayName','b','FaceColor',[1 0 0],'BarWidth',0.5);
set(bar1(1),'DisplayName','c','FaceColor',[0 0.5 0],'BarWidth',0.5);

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-3.3333336750883 20]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',12,'FontWeight','bold',...
    'GridAlpha',1,'GridColor',...
    [0.941176470588235 0.941176470588235 0.941176470588235],'XGrid','on',...
    'YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'NumColumns',2);

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.765277777777777 3.34722222222222 4.52083333333333 2.47916666666667],...
    'Units','inches');
hold(axes2,'on');

% Create multiple lines using matrix input to bar
bar2 = bar(ymatrix2,'Parent',axes2);
set(bar2(6),'DisplayName','Matpower (a)','FaceColor','none','BarWidth',1);
set(bar2(5),'DisplayName','Matpower (b)','FaceColor','none','BarWidth',1);
set(bar2(4),'DisplayName','Matpower (c)','FaceColor','none','BarWidth',1);
set(bar2(3),'DisplayName','a','FaceColor',[0 0 1],'BarWidth',0.5);
set(bar2(2),'DisplayName','b','FaceColor',[1 0 0],'BarWidth',0.5);
set(bar2(1),'DisplayName','c','FaceColor',[0 0.5 0],'BarWidth',0.5);

% Create ylabel
ylabel('Q (kVAr)','FontWeight','bold','FontName','Times New Roman');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[-1.72585988115386 8]);
box(axes2,'on');
% Set the remaining axes properties
set(axes2,'FontName','Times New Roman','FontSize',12,'FontWeight','bold',...
    'GridAlpha',1,'GridColor',...
    [0.941176470588235 0.941176470588235 0.941176470588235],'XGrid','on',...
    'YGrid','on');
% Create legend
legend2 = legend(axes2,'show');
set(legend2,'NumColumns',2);

% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.758333333333333 0.48125 4.52083333333333 2.47916666666667],...
    'Units','inches');
hold(axes3,'on');

% Create multiple lines using matrix input to bar
bar3 = bar(ymatrix3,'Parent',axes3);
set(bar3(6),'DisplayName','Matpower (a)','FaceColor','none','BarWidth',1);
set(bar3(5),'DisplayName','Matpower (b)','FaceColor','none','BarWidth',1);
set(bar3(4),'DisplayName','Matpower (c)','FaceColor','none','BarWidth',1);
set(bar3(3),'DisplayName','a','FaceColor',[0 0 1],'BarWidth',0.5);
set(bar3(2),'DisplayName','b','FaceColor',[1 0 0],'BarWidth',0.5);
set(bar3(1),'DisplayName','c','FaceColor',[0 0.5 0],'BarWidth',0.5);

% Create ylabel
ylabel('S (kVA)','FontWeight','bold','FontName','Times New Roman');

% Create xlabel
xlabel('Bus Numbers','FontWeight','bold','FontName','Times New Roman');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[0 8]);
box(axes3,'on');
% Set the remaining axes properties
set(axes3,'FontName','Times New Roman','FontSize',12,'FontWeight','bold',...
    'GridAlpha',1,'GridColor',...
    [0.941176470588235 0.941176470588235 0.941176470588235],'XGrid','on',...
    'YGrid','on');
% Create legend
legend3 = legend(axes3,'show');
set(legend3,'NumColumns',2);

