function V1=V1(Va,da,Vb,db,Vc,dc)
V1=(1/3)*sqrt(Va.^2+Vb.^2+Vc.^2 ...
   +2.*(Va.*Vb.*cosd(da).*cosd(db-120) ...
     + Va.*Vc.*cosd(da).*cosd(dc+120) ...
     + Vb.*Vc.*cosd(db-120).*cosd(dc+120) ...
     + Va.*Vb.*sind(da).*sind(db-120) ...
     + Va.*Vc.*sind(da).*sind(dc+120) ...
     + Vb.*Vc.*sind(db-120).*sind(dc+120) ...  
   ));
end
