function createfigure(YMatrix1, YMatrix2, YMatrix3)
%CREATEFIGURE(YMatrix1, YMatrix2, YMatrix3)
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
%  YMATRIX3:  matrix of y data

%  Auto-generated by MATLAB on 27-Mar-2020 22:35:52

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(3,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',subplot1,'LineWidth',2);
set(plot1(1),'DisplayName','Matpower');
set(plot1(2),'DisplayName','Linear');

% Create ylabel
ylabel({'Active','Power (kVAR)'});

% Create title
title('Line Flows');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0 33]);
box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'FontName','Georgia','XGrid','on','XMinorGrid','on','XTick',...
    [1 5 10 15 20 25 30 33],'YGrid','on','YMinorGrid','on');
% Create legend
legend(subplot1,'show');

% Create subplot
subplot2 = subplot(3,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(YMatrix2,'Parent',subplot2,'LineWidth',2);
set(plot2(1),'DisplayName','Matpower');
set(plot2(2),'DisplayName','Linear');

% Create ylabel
ylabel({'Reactive ','Power (kVAR)'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0 33]);
box(subplot2,'on');
% Set the remaining axes properties
set(subplot2,'FontName','Georgia','XGrid','on','XMinorGrid','on','XTick',...
    [1 5 10 15 20 25 30 33],'YGrid','on','YMinorGrid','on');
% Create legend
legend(subplot2,'show');

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.11 0.77546875 0.215735294117647]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot3 = plot(YMatrix3,'Parent',axes1,'LineWidth',2);
set(plot3(1),'DisplayName','Matpower');
set(plot3(2),'DisplayName','Linear');

% Create ylabel
ylabel({'Apparent ','power (kVAR)'});

% Create xlabel
xlabel('Bus Numbers');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 33]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Georgia','XGrid','on','XMinorGrid','on','XTick',...
    [1 5 10 15 20 25 30 33],'XTickLabel',...
    {'1','5','10','15','20','25','30','33'},'YGrid','on','YMinorGrid','on');
% Create legend
legend(axes1,'show');

