function createfigure(ymatrix1, ymatrix2, ymatrix3)
%CREATEFIGURE(ymatrix1, ymatrix2, ymatrix3)
%  YMATRIX1:  bar matrix data
%  YMATRIX2:  bar matrix data
%  YMATRIX3:  bar matrix data

%  Auto-generated by MATLAB on 27-Mar-2020 23:01:38

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(3,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1,'Parent',subplot1);
set(bar1(2),'DisplayName','Matpower');
set(bar1(1),'DisplayName','Linear');

% Create ylabel
ylabel('P (Mw)','FontName','Georgia');

% Create title
title('Bus Injections');

box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'FontName','Georgia','XGrid','on','XMinorGrid','on','YGrid',...
    'on','YMinorGrid','on');
% Create subplot
subplot2 = subplot(3,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create multiple lines using matrix input to bar
bar2 = bar(ymatrix2,'Parent',subplot2);
set(bar2(2),'DisplayName','Matpower');
set(bar2(1),'DisplayName','Linear');

% Create ylabel
ylabel('Q (Mvar)','FontName','Georgia');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[-1 1]);
box(subplot2,'on');
% Set the remaining axes properties
set(subplot2,'FontName','Georgia','XGrid','on','XMinorGrid','on','YGrid',...
    'on','YMinorGrid','on');
% Create subplot
subplot3 = subplot(3,1,3,'Parent',figure1);
hold(subplot3,'on');

% Create multiple lines using matrix input to bar
bar3 = bar(ymatrix3,'Parent',subplot3);
set(bar3(2),'DisplayName','Matpower');
set(bar3(1),'DisplayName','Linear');

% Create ylabel
ylabel('S (MVA)','FontName','Georgia');

% Create xlabel
xlabel('Bus Number','FontName','Georgia');

box(subplot3,'on');
% Set the remaining axes properties
set(subplot3,'FontName','Georgia','XGrid','on','XMinorGrid','on','YGrid',...
    'on','YMinorGrid','on');
% Create legend
legend1 = legend(subplot3,'show');
set(legend1,...
    'Position',[0.78671875 0.230508424977795 0.111021423309823 0.0833333333333333]);

