function createfigure_6(YMatrix1,ttr)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 03-Feb-2020 12:33:06

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','V_a mat','LineWidth',5);
set(plot1(2),'DisplayName','V_b mat','LineWidth',5);
set(plot1(3),'DisplayName','V_c mat','LineWidth',5,...
    'Color',[0 0.498039215803146 0]);
set(plot1(4),'DisplayName','V_a lin','LineWidth',2,'LineStyle',':',...
    'Color',[0 0.447058826684952 0.74117648601532]);
set(plot1(5),'DisplayName','V_b lin','LineWidth',2,'LineStyle',':',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);
set(plot1(6),'DisplayName','V_c lin','LineWidth',2,'LineStyle',':',...
    'Color',[0 0.498039215803146 0]);

% Create xlabel
xlabel('Bus Numbers');

% Create title
title(ttr);
set(axes1,'FontName','Georgia','XGrid','on','XMinorGrid','on','YGrid','on',...
    'YMinorGrid','on');
box(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.139324819048246 0.75013572386565 0.189453125 0.144886363636363],...
    'NumColumns',2);
end