function createfigure(xvector1, ymatrix1, ymatrix2, ymatrix3, ymatrix4)
%CREATEFIGURE(xvector1, ymatrix1, ymatrix2, ymatrix3, ymatrix4)
%  XVECTOR1:  bar xvector
%  YMATRIX1:  bar matrix data
%  YMATRIX2:  bar matrix data
%  YMATRIX3:  bar matrix data
%  YMATRIX4:  bar matrix data

%  Auto-generated by MATLAB on 23-Jun-2022 13:59:17

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create multiple lines using matrix input to bar
bar1 = bar(xvector1,ymatrix1,'Parent',subplot1);
set(bar1(3),'FaceColor',[0 0 1]);
set(bar1(2),'FaceColor',[1 0 0]);
set(bar1(1),'FaceColor',[0 0.501960784313725 0]);

% Create ylabel
ylabel('Crossphase','FontWeight','bold');

% Create title
title('Operational','FontName','Times New Roman');

box(subplot1,'on');
hold(subplot1,'off');
% Set the remaining axes properties
set(subplot1,'FontName','Times New Roman','XGrid','on','XMinorGrid','on',...
    'YGrid','on','YMinorGrid','on');
% Create subplot
subplot2 = subplot(2,2,3,'Parent',figure1);
hold(subplot2,'on');

% Create multiple lines using matrix input to bar
bar2 = bar(xvector1,ymatrix2,'Parent',subplot2);
set(bar2(3),'FaceColor',[0 0 1]);
set(bar2(2),'FaceColor',[1 0 0]);
set(bar2(1),'FaceColor',[0 0.501960784313725 0]);

% Create ylabel
ylabel('OPF','FontWeight','bold','FontName','Times New Roman');

box(subplot2,'on');
hold(subplot2,'off');
% Set the remaining axes properties
set(subplot2,'XGrid','on','XMinorGrid','on','YGrid','on','YMinorGrid','on');
% Create subplot
subplot3 = subplot(2,2,2,'Parent',figure1);
hold(subplot3,'on');

% Create multiple lines using matrix input to bar
bar3 = bar(xvector1,ymatrix3,'Parent',subplot3);
set(bar3(3),'FaceColor',[0 0 1]);
set(bar3(2),'FaceColor',[1 0 0]);
set(bar3(1),'FaceColor',[0 0.501960784313725 0]);

% Create title
title('Non-Operational','FontName','Times New Roman');

box(subplot3,'on');
hold(subplot3,'off');
% Set the remaining axes properties
set(subplot3,'XGrid','on','XMinorGrid','on','YGrid','on','YMinorGrid','on');
% Create subplot
subplot4 = subplot(2,2,4,'Parent',figure1);
hold(subplot4,'on');

% Create multiple lines using matrix input to bar
bar4 = bar(xvector1,ymatrix4,'Parent',subplot4);
set(bar4(3),'FaceColor',[0 0 1]);
set(bar4(2),'FaceColor',[1 0 0]);
set(bar4(1),'FaceColor',[0 0.501960784313725 0]);

box(subplot4,'on');
hold(subplot4,'off');
% Set the remaining axes properties
set(subplot4,'XGrid','on','XMinorGrid','on','YGrid','on','YMinorGrid','on');
