function createsgtitle(parent1)
%CREATESGTITLE(parent1)
%  PARENT1:  parent container

%  Auto-generated by MATLAB on 23-Jun-2022 14:47:37

% Create sgtitle
sgtitle(parent1,'Inverter Power Reference comparison','Interpreter','latex');

